### ISSUE TITLE
any() matcher for java Class parameter fails with IllegalAccessError

### ISSUE THREAD

**Issue by a1flecke** [oleksiyp/mockk#29]
if I have a method parameter that is of type `java.lang.Class<?>` like:
```java
public boolean isRegistered(Class<?> componentClass);
``` 

or in Kotlin:
```kotlin
fun gimmeJavaClass(klass: Class<*>): Boolean = true
```
then the `any()` matcher causes a `java.lang.Class` exception:
```
java.lang.IllegalAccessError: java.lang.Class

	at sun.reflect.GeneratedSerializationConstructorAccessor12.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at io.mockk.proxy.MockKProxyMaker.newEmptyInstance(MockKProxyMaker.java:230)
	at io.mockk.proxy.MockKProxyMaker.instance(MockKProxyMaker.java:63)
	at io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
	at io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
	at io.mockk.impl.instantiation.JvmInstantiator.instantiate(JvmInstantiator.kt:15)
	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1$1.invoke(RecordingState.kt:46)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$1.invoke(JvmAnyValueGenerator.kt:24)
	at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:27)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:20)
	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1.invoke(RecordingState.kt:45)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:20)
	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:44)
	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:47)
	at io.mockk.MockKTestSuite$1$11$1.invoke(MockKTestSuite.kt:607)
	at io.mockk.MockKTestSuite$1$11$1.invoke(MockKTestSuite.kt:10)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:22)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:31)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
```

Here is a test case:
1) Modify your `io.mockk.MockCls` class in `CommonCallRecorderTest` to add 
```kotlin
fun gimmeJavaClass(klass: Class<*>): Boolean = true
```
2) Add this test.  It will fail:
```kotlin
"any class" {
        every { mock.gimmeJavaClass(any()) }.returns(false)
        assertEquals(false, mock.gimmeJavaClass(Long::class.java))
    }
```

**Comment by oleksiyp** [comment]
I fixed it on master branch. Waiting for changes to be released

**Comment by oleksiyp** [comment]
Version 1.7.6 released, please check and close if it fixes your issue

**Comment by a1flecke** [comment]
@oleksiyp fixed.  It is great to use something that is supported so well.  Keep up the great work!

**Comment by mepi262** [comment]
@oleksiyp 
The mockk v1.7.6 has already been released, so it might be a good idea to close the milestone [v1.7.6](https://github.com/mockk/mockk/milestone/1).
What do you think about it?
