### ISSUE TITLE
strange issue with throws block

### ISSUE THREAD

**Issue by stalexxx** [oleksiyp/mockk#36]
Here https://github.com/stalexxx/ad-scrapper/blob/3f38e75d806ad9b3ea99b019280728fe78cd29d0/avito/src/test/kotlin/com/stalex/avito/RetryTest.kt I firstly made test "test always bad with mockk", but it failed stangly, although it should do the same as "test always bad"(that works):
in debugger it goes until line 35, but then fails with exception on line 33

**Comment by oleksiyp** [comment]
Let me check what is wrong

**Comment by oleksiyp** [comment]
Can you paste an exception message with stacktrace

**Comment by stalexxx** [comment]
well, i got that
java.lang.IllegalStateException
	at com.stalex.avito.RetryTest$3.invoke(RetryTest.kt:33)
	at com.stalex.avito.RetryTest$3.invoke(RetryTest.kt:10)
	at io.kotlintest.Spec$runTest$callable$1$1.invoke(Spec.kt:124)
	at io.kotlintest.Spec$runTest$callable$1$1.invoke(Spec.kt:15)
	at io.kotlintest.Spec$runTest$initialInterceptor$1$1.invoke(Spec.kt:116)
	at io.kotlintest.Spec$runTest$initialInterceptor$1$1.invoke(Spec.kt:15)
	at io.kotlintest.Spec.interceptTestCase(Spec.kt:78)
	at io.kotlintest.Spec$runTest$initialInterceptor$1.invoke(Spec.kt:116)
	at io.kotlintest.Spec$runTest$initialInterceptor$1.invoke(Spec.kt:15)
	at io.kotlintest.Spec$runTest$callable$1.call(Spec.kt:124)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


but you can run it yourself

**Comment by oleksiyp** [comment]
Very weird error. Not able to understand how that's possible

**Comment by oleksiyp** [comment]
Ok, now understand

**Comment by oleksiyp** [comment]
It's about how Kotlin and MockK interact regarding Boxed numbers

**Comment by oleksiyp** [comment]
As a workaround you can use `Parser<String, Int?>`. It should pass. Meanwhile I get closer on what can be done with non-nullable integer

```
        "test always bad with mockk" {
            val parser = mockk<Parser<String, Int?>>()
            every { parser.parse(any()) } throws IllegalStateException()

            val result = RetryableParser(parser, default = { -1 }).parse("")

            result shouldBe -1
        }.config(enabled = true)
```

**Comment by stalexxx** [comment]
well, Int is some random type, doesn't matter

**Comment by oleksiyp** [comment]
Are you sure it doesn't matter?

Because what I understood Kotlin is returning Int object from Parse and then any first possible time converts it to `int` via `intValue()` , but because you pass it from mock to other type of Parser it keep the object `Int` and only when it assigned to `val` calls `intValue()` which results in exception(because it is mocked). That way intValue() get out of `try {} catch(...) {}` and throws Excecption

**Comment by oleksiyp** [comment]
Version 1.7.10 released, please check if it fixes your case and close the ticket.
