### ISSUE TITLE
Dex issue with mockk for instrumentation test environment

### ISSUE THREAD

**Issue by tomkoptel** [oleksiyp/mockk#39]
I have a use case with using Kotlin classes in my UI tests. To mock them I have opted with `mockk`, because of the class finalization that `mockk` gracefully solves. 

The problem is that it lacks some setup. I am facing dex issue. I do suspect that it is connected to the same problem `mockito` library had. It was [solved by LinkedIn and their dexmaker solution](https://github.com/linkedin/dexmaker). Is there any way we can run `mockk` on the emulator or real device dex environment?

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.instrument.ClassFileTransformer" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar"],nativeLibraryDirectories=[/data/app/my.app.test-35h1VdSJ4oyoucfymSsugg==/lib/arm64, /data/app/my.app.staging.debug-7njk-OasH4iMH8Dkfhr-4A==/lib/arm64, /data/app/my.app.test-35h1VdSJ4oyoucfymSsugg==/base.apk!/lib/arm64-v8a, /data/app/my.app.staging.debug-7njk-OasH4iMH8Dkfhr-4A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by oleksiyp** [comment]
This is on my todo list, but requires really sufficient effort. Thanks for the link, I wasnt aware it is solved for mockito. Will check it later

**Comment by neild001** [comment]
@oleksiyp Would be really nice to see support for Android instrumented unit tests. I had a quick look into how mockito does this in the latest version. In version 2.1 and above you use a different build of mockito in androidTest mockito-android , not mockito-core. I think mockito uses byte buddy, but for the android version it use net.bytebuddy:byte-buddy-android. I think you use byte buddy too. So it may simply be a case of swapping out the version of the byte buddy lib that you use so it generates Dex bytecode instead. You could do this with build flavors.

**Comment by oleksiyp** [comment]
hm, that's interesting, especially if it is just lib swap

**Comment by oleksiyp** [comment]
So I've checked net.bytebuddy:byte-buddy-android and how mockito use it. It's pretty simple subclass instrumentation which doesn't allow to mock final functions and other non-trivial stuff.

I am looking towards more sophisticated solution with https://github.com/linkedin/dexmaker, it supports inlining i.e. can mock inplace and even have support for static methods for mockito as extension.

**Comment by neild001** [comment]
Ah ok, fair enough. I can see that having support for mocking final functions in Kotlin is pretty important.  Good luck with the dexmaker approach. Having support for Android instrumented unit tests would be awesome.

**Comment by oleksiyp** [comment]
Android instrumentation will be very soon :-) after this weekend most probably. After realeasing I'll need to stabilize for some time. So any testing and reporting is very welcome.
